"""Deterministic report builders for the local toy workflow."""

from __future__ import annotations

from oh_my_paper.artifacts.claims import Claim
from oh_my_paper.artifacts.evidence import EvidenceItem
from oh_my_paper.gates.evidence import GateResult


def _claim_line(claim: Claim) -> str:
    return f"- `{claim.claim_id}` ({claim.status}): {claim.text}"


def build_writing_draft(claims: list[Claim], gate: GateResult) -> str:
    blocked = {finding.claim_id for finding in gate.findings if finding.severity == "blocking"}
    safe_claims = [claim for claim in claims if claim.claim_id not in blocked]
    risk_lines = [f"- `{finding.claim_id}`: {finding.message}" for finding in gate.findings]
    body = "\n".join(_claim_line(claim) for claim in safe_claims) or "- No claims are safe to draft yet."
    risks = "\n".join(risk_lines) or "- No blocking evidence risks detected."
    return f"""# Demo Writing Draft

This synthetic draft is generated from supported or caveated claims only. It is not a submission-ready paper section.

## Safe contribution sketch

{body}

## Claims withheld or caveated

{risks}
"""


def build_figure_plan(claims: list[Claim]) -> str:
    supported = [claim for claim in claims if claim.status in {"supported", "partial"}]
    rows = ["| Visual | Linked claim | Takeaway | Readability check |", "| --- | --- | --- | --- |"]
    for index, claim in enumerate(supported, 1):
        rows.append(
            f"| Figure {index} | {claim.claim_id} | Show evidence status for: {claim.text} | Label axes, state synthetic scope, keep caption claim-specific. |"
        )
    return "# Figure Plan\n\n" + "\n".join(rows) + "\n"


def build_table_plan(evidence: list[EvidenceItem]) -> str:
    rows = ["| Table | Claim | Evidence status | Caveat to display |", "| --- | --- | --- | --- |"]
    for item in evidence:
        rows.append(f"| Evidence ledger | {item.claim_id} | {item.status} | {item.caveat or 'None'} |")
    return "# Table Plan\n\n" + "\n".join(rows) + "\n"


def build_layout_report() -> str:
    return """# Layout Report

## Generic page-budget check

- Use a generic paper budget because no venue template is configured.
- Keep the claim ledger, evidence table, and limitation text visible before claiming readiness.
- Treat exact page compliance as unknown until a venue template is provided.

## Gate

Status: warn — venue/page constraints are not yet specific.
"""


def build_review_simulation(gate: GateResult) -> str:
    rows = ["| Severity | Issue | Recommended fix |", "| --- | --- | --- |"]
    if gate.findings:
        for finding in gate.findings:
            severity = "high" if finding.severity == "blocking" else "medium"
            rows.append(f"| {severity} | `{finding.claim_id}`: {finding.message} | Remove, soften, or add evidence before submission. |")
    else:
        rows.append("| low | No unsupported claims detected in the synthetic ledger. | Continue normal review. |")
    return "# Review Simulation\n\n" + "\n".join(rows) + "\n"


def build_fix_plan(gate: GateResult) -> str:
    items = [f"1. Resolve `{finding.claim_id}` — {finding.message}" for finding in gate.findings]
    if not items:
        items = ["1. No blocking evidence fixes detected; run human review before submission-ready claims."]
    return "# Fix Plan\n\n" + "\n".join(items) + "\n"


def build_rebuttal_plan(gate: GateResult) -> str:
    rows = ["| Reviewer concern | Response strategy | Promise risk |", "| --- | --- | --- |"]
    if gate.findings:
        for finding in gate.findings:
            rows.append(
                f"| Reviewer questions `{finding.claim_id}` evidence. | Concede current limitation and point to available evidence only. | Do not promise completed experiments without approval. |"
            )
    else:
        rows.append("| Evidence support requested. | Cite mapped evidence and state scope conservatively. | Low. |")
    return "# Rebuttal Plan\n\n" + "\n".join(rows) + "\n"


def build_promised_revisions(gate: GateResult) -> str:
    if gate.findings:
        lines = [f"- `{finding.claim_id}`: revise wording or mark as future work; no unapproved experiment promise." for finding in gate.findings]
    else:
        lines = ["- No risky promises generated by the demo workflow."]
    return "# Promised Revisions\n\n" + "\n".join(lines) + "\n"


def build_eval_report(phase_statuses: dict[str, str], gate: GateResult) -> str:
    rows = ["| Check | Status | Notes |", "| --- | --- | --- |"]
    for phase, status in phase_statuses.items():
        rows.append(f"| phase `{phase}` trace event | pass | gate status `{status}` recorded |")
    rows.append(f"| evidence gate | {gate.status} | {len(gate.findings)} finding(s) visible to human |")
    return "# Eval Report\n\n" + "\n".join(rows) + "\n"
